name: cleverevans
favicon: null
layout_spectrum: 0.1331106482539326
typography_spectrum: 0.20128261833451688
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.002552760299295187
  lightness: 0.619717082940042
  saturation: 0.8738355471286923
  rhythmicContrast: 0.5783474049530923
purpose: []
