name: cleverevans
favicon: null
layout_spectrum: 0.99063
typography_spectrum: 0.63686
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#939498'
    - '#4d4054'
    - '#000000'
    - '#616161'
    - '#cdcdcd'
  brandStrength: 0.002552760299295187
  lightness: 0.619717082940042
  saturation: 0.875
  rhythmicContrast: 0.5783474049530923
purpose: []
